# Generated by Django 3.0 on 2019-12-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('diretor', models.CharField(max_length=45)),
                ('minutos', models.IntegerField()),
                ('dataLancamento', models.DateField()),
                ('atores', models.ManyToManyField(to='ator.Ator')),
            ],
        ),
    ]
