# Generated by Django 3.0 on 2019-12-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('idade', models.PositiveIntegerField()),
                ('salario', models.FloatField()),
                ('dataNascimento', models.DateField()),
            ],
        ),
    ]
